// <auto-generated />
using Catalog.Infrastructure.Models.Catalog.Infrastructure.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(PhoneContext))]
    [Migration("20180703063757_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("Catalog.Infrastructure.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.HasKey("Id");

                    b.ToTable("Phones");

                    b.HasData(
                        new { Id = 1, Description = "Galaxy S9 256GB (Unlocked)", ImgUrl = "http://s7d2.scene7.com/is/image/SamsungUS/S9Plus_front_gold?$product-details-jpg$", Name = "Samsung Galaxy S9 256GB", Price = 959.99m },
                        new { Id = 2, Description = "Galaxy S9 128GB (Unlocked)", ImgUrl = "http://s7d2.scene7.com/is/image/SamsungUS/S9Plus_l30_gold?$product-details-jpg$", Name = "Samsung Galaxy S9 128GB", Price = 889.99m },
                        new { Id = 3, Description = "Galaxy S8 64GB (Unlocked)", ImgUrl = "http://s7d2.scene7.com/is/image/SamsungUS/S8Plus_Black_Front_032317?$product-details-jpg$", Name = "Samsung Galaxy S8 64GB", Price = 589.99m },
                        new { Id = 4, Description = "Samsung Galaxy S8 Active 64GB (Sp)", ImgUrl = "http://s7d2.scene7.com/is/image/SamsungUS/spr_g892u_s8_active_gy_v_front_lock?$default-jpg$", Name = "Samsung Galaxy S8 Active 64GB", Price = 850m },
                        new { Id = 5, Description = "Galaxy S7 32GB (TMob)", ImgUrl = "http://s7d2.scene7.compubli/is/image/SamsungUS/SMG930s7_hero_102116?$default-jpg$", Name = "Samsung Galaxy S7 32GB", Price = 473m }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
